// Generated by playwright-expert BOOTSTRAP — Recipe A (Spring Boot + Vite).
// Markers below have been substituted; the file is now config code, not
// a template. Re-run BOOTSTRAP --upgrade to regenerate.

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,

  // Reporter list. The 'github' reporter prints `::notice::` lines
  // unconditionally; only GitHub Actions parses them as annotations
  // — locally those lines are noise. Conditional spread keeps the
  // reporter active only on CI. For Jenkins / GitLab, swap or add
  // ['junit', { outputFile: 'results/junit.xml' }].
  reporter: [
    ['list'],
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'results/report.json' }],
    ...(process.env.CI ? [['github'] as ['github']] : []),
  ],

  // Artefact policy. Officially documented default for CI is only
  // trace: 'on-first-retry' (see playwright.dev/docs/ci-intro). The
  // screenshot and video values below are community convention —
  // adjust per spec / per debug session.
  use: {
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: [
    {
      // -x processAot per qa-strategy.md Known Limitations (GraalVM
      // native build plugin pre-existing bug; workaround until AOT
      // config or OTel switch lands).
      name: 'Backend',
      command: './gradlew bootRun -x processAot',
      cwd: '../backend',
      url: 'http://localhost:8080/actuator/health',
      timeout: 180_000,
      reuseExistingServer: !process.env.CI,
      stdout: 'pipe',
      stderr: 'pipe',
    },
    {
      name: 'Frontend',
      command: 'npm run dev',
      cwd: '../frontend',
      url: 'http://localhost:5173',
      timeout: 60_000,
      reuseExistingServer: !process.env.CI,
    },
  ],
});
