// Generated by playwright-expert BOOTSTRAP — Recipe A (Spring Boot + Vite).
// Markers below have been substituted; the file is now config code, not
// a template. Re-run BOOTSTRAP --upgrade to regenerate.

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  // S140-T09: 全局單 worker。`fullyParallel: false` 只擋同檔內 test 並行；
  // 跨 spec file 預設仍依 worker 數同跑，造成 resetAll/seedSkill 互踩
  // （TRUNCATE 拿 AccessExclusiveLock 與 INSERT RowShareLock 互鎖 → deadlock；
  // 同名 seed → 409 DUPLICATE_RESOURCE）。S140 6 支 spec 共用後端 state，
  // 一律 workers=1 才能保證 fixture isolation。CI 本來就 1，這裡與 CI 對齊。
  workers: 1,

  // Reporter list. The 'github' reporter prints `::notice::` lines
  // unconditionally; only GitHub Actions parses them as annotations
  // — locally those lines are noise. Conditional spread keeps the
  // reporter active only on CI. For Jenkins / GitLab, swap or add
  // ['junit', { outputFile: 'results/junit.xml' }].
  reporter: [
    ['list'],
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'results/report.json' }],
    ...(process.env.CI ? [['github'] as ['github']] : []),
  ],

  // Artefact policy. Officially documented default for CI is only
  // trace: 'on-first-retry' (see playwright.dev/docs/ci-intro). The
  // screenshot and video values below are community convention —
  // adjust per spec / per debug session.
  use: {
    baseURL: 'http://localhost:5173',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: [
    {
      // -x processAot per qa-strategy.md Known Limitations (GraalVM
      // native build plugin pre-existing bug; workaround until AOT
      // config or OTel switch lands).
      //
      // S140: SPRING_PROFILES_ACTIVE 顯式宣告 local,dev,e2e。dev 提供
      // DB 連線值 + LAB security（oauth disabled），e2e 補上 deterministic
      // stub embedder + semantic threshold=-1.0。沒寫的話會走 base yaml
      // default（local,dev），missing application-e2e.yaml + stub embedder
      // → AC-5 永遠 empty results，AC-1/3/4/6 也不一定能跑通。
      name: 'Backend',
      command: './gradlew bootRun -x processAot',
      cwd: '../backend',
      env: { SPRING_PROFILES_ACTIVE: 'local,dev,e2e' },
      url: 'http://localhost:8080/actuator/health',
      timeout: 180_000,
      reuseExistingServer: !process.env.CI,
      stdout: 'pipe',
      stderr: 'pipe',
    },
    {
      name: 'Frontend',
      command: 'npm run dev',
      cwd: '../frontend',
      url: 'http://localhost:5173',
      timeout: 60_000,
      reuseExistingServer: !process.env.CI,
    },
  ],
});
