// Generated by playwright-expert BOOTSTRAP — Recipe A (Spring Boot + Vite).
// Markers below have been substituted; the file is now config code, not
// a template. Re-run BOOTSTRAP --upgrade to regenerate.

import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  // S140-T09: 全局單 worker。`fullyParallel: false` 只擋同檔內 test 並行；
  // 跨 spec file 預設仍依 worker 數同跑，造成 resetAll/seedSkill 互踩
  // （TRUNCATE 拿 AccessExclusiveLock 與 INSERT RowShareLock 互鎖 → deadlock；
  // 同名 seed → 409 DUPLICATE_RESOURCE）。S140 6 支 spec 共用後端 state，
  // 一律 workers=1 才能保證 fixture isolation。CI 本來就 1，這裡與 CI 對齊。
  workers: 1,

  // Reporter list. The 'github' reporter prints `::notice::` lines
  // unconditionally; only GitHub Actions parses them as annotations
  // — locally those lines are noise. Conditional spread keeps the
  // reporter active only on CI. For Jenkins / GitLab, swap or add
  // ['junit', { outputFile: 'results/junit.xml' }].
  reporter: [
    ['list'],
    ['html', { outputFolder: 'playwright-report', open: 'never' }],
    ['json', { outputFile: 'results/report.json' }],
    ...(process.env.CI ? [['github'] as ['github']] : []),
  ],

  // Artefact policy. Officially documented default for CI is only
  // trace: 'on-first-retry' (see playwright.dev/docs/ci-intro). The
  // screenshot and video values below are community convention —
  // adjust per spec / per debug session.
  use: {
    baseURL: 'http://localhost:8080',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },

  projects: [
    {
      name: 'fixture unit',
      testMatch: /fixtures\/.*\.spec\.ts/,
      teardown: 'teardown fixtures',
    },
    {
      name: 'setup fixtures',
      testMatch: /fixtures\/setup\.fixtures\.ts/,
      teardown: 'teardown fixtures',
    },
    {
      name: 'teardown fixtures',
      testMatch: /fixtures\/teardown\.fixtures\.ts/,
    },
    {
      name: 'chromium',
      testMatch: /tests\/.*\.spec\.ts/,
      dependencies: ['setup fixtures'],
      use: { ...devices['Desktop Chrome'] },
    },
  ],

  webServer: {
    // S202-T02: V07 gate starts the production packaged app image via Compose.
    name: 'Compose',
    command: 'npm run compose:webserver',
    url: 'http://localhost:8080/actuator/health',
    timeout: 240_000,
    reuseExistingServer: !process.env.CI,
    stdout: 'pipe',
    stderr: 'pipe',
  },
});
