#!/usr/bin/env python3
"""S157 — Convert /tmp/fixture-output.json (from fetch_embedding_fixture.sh)
into 2 fixture artifacts:

1. backend/src/test/resources/search/embedding-fixture.sql
   — 5 INSERT INTO skills + 5 INSERT INTO vector_store rows with real 768-d Gemini embeddings.

2. backend/src/test/java/io/github/samzhu/skillshub/search/EmbeddingFixture.java
   — Java map {query text → real Gemini 768-d embedding} for fixture-based EmbeddingModel
     to skip Gemini call during test runtime.

Usage (after fetch script ran):
    python3 tools/embedding_fixture_to_sql.py
"""

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_INPUT = "/tmp/fixture-output.json"
SQL_OUT = os.path.join(REPO_ROOT, "backend/src/test/resources/search/embedding-fixture.sql")
JAVA_OUT = os.path.join(REPO_ROOT,
                       "backend/src/test/java/io/github/samzhu/skillshub/search/EmbeddingFixture.java")

OWNER = "fixture-owner"
ACL = '["public:*:read"]'


def main():
    if not os.path.exists(JSON_INPUT):
        print(f"ERROR: {JSON_INPUT} not found. Run tools/fetch_embedding_fixture.sh first.",
              file=sys.stderr)
        sys.exit(1)

    with open(JSON_INPUT) as f:
        data = json.load(f)

    sql_lines = [
        "-- S157 — Real Gemini API fixture for semantic search regression test.",
        "-- Auto-generated by tools/embedding_fixture_to_sql.py; do NOT hand-edit.",
        "-- 5 docs + 3 queries embedded with gemini-embedding-001 (outputDimensionality=768).",
        "-- Refresh procedure: see EmbeddingFixture.java javadoc.",
        "",
        "-- Skills 前置 (FK: vector_store.skill_id REFERENCES skills.id)",
    ]

    for doc in data["documents"]:
        sid = doc["id"]
        name = doc["name"].replace("'", "''")
        desc = doc["text"].replace("'", "''")
        cat = doc["category"]
        sql_lines.append(
            f"INSERT INTO skills (id, name, description, author, owner_id, category, "
            f"latest_version, risk_level, status, download_count, created_at, updated_at, acl_entries) "
            f"VALUES ('{sid}', '{name}', '{desc}', '{OWNER}', '{OWNER}', '{cat}', '1.0.0', "
            f"'LOW', 'PUBLISHED', 0, NOW(), NOW(), '{ACL}'::jsonb);"
        )

    sql_lines.append("")
    sql_lines.append("-- vector_store rows with real Gemini 768-d embeddings")

    for doc in data["documents"]:
        sid = doc["id"]
        name = doc["name"]
        desc = doc["text"]
        cat = doc["category"]
        vec = ",".join(repr(float(v)) for v in doc["embedding"])
        content = f"{name} {desc}".replace("'", "''")
        metadata = json.dumps({
            "skillId": sid,
            "name": name,
            "description": desc,
            "author": OWNER,
            "category": cat,
            "downloadCount": 0,
        }).replace("'", "''")
        sql_lines.append(
            f"INSERT INTO vector_store (id, content, metadata, embedding, owner, skill_id, acl_entries) "
            f"VALUES ('{sid}'::uuid, '{content}', '{metadata}'::jsonb, "
            f"'[{vec}]'::vector, '{OWNER}', '{sid}', '{ACL}'::jsonb);"
        )

    os.makedirs(os.path.dirname(SQL_OUT), exist_ok=True)
    with open(SQL_OUT, "w") as f:
        f.write("\n".join(sql_lines) + "\n")
    print(f"Wrote {SQL_OUT} ({len(sql_lines)} lines)")

    # Java fixture for query embeddings
    java_lines = [
        "package io.github.samzhu.skillshub.search;",
        "",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "/**",
        " * S157 — Real Gemini API query embeddings auto-generated from",
        " * {@code tools/embedding_fixture_to_sql.py}。",
        " *",
        " * <p>對應 {@code src/test/resources/search/embedding-fixture.sql} 的 5 doc seed；",
        " * 這裡是 3 個對應 query 的 real Gemini 768-d 向量。Fixture-based EmbeddingModel",
        " * 用這份 map 直接 lookup (text → embedding)，避開測試時打 Gemini。",
        " *",
        " * <p><b>Refresh 程序</b>（半年或 model 升級時）：",
        " * <pre>",
        " *   KEY=$(grep '^skillshub.genai.api-key=' backend/config/application-secrets.properties | cut -d= -f2-)",
        " *   bash tools/fetch_embedding_fixture.sh \"$KEY\"",
        " *   python3 tools/embedding_fixture_to_sql.py",
        " * </pre>",
        " *",
        " * @see SemanticSearchRealFixtureIT",
        " */",
        "final class EmbeddingFixture {",
        "",
        "    private EmbeddingFixture() {}",
        "",
        "    /** Query text → real Gemini 768-d embedding。 */",
        "    static final Map<String, float[]> QUERIES;",
        "    /** Each query 預期 top-match skill id（FK 對應 SQL fixture）。 */",
        "    static final Map<String, String> EXPECTED_TOP;",
        "",
        "    static {",
        "        Map<String, float[]> q = new LinkedHashMap<>();",
        "        Map<String, String> e = new LinkedHashMap<>();",
    ]

    for q in data["queries"]:
        vec_parts = ", ".join(f"{float(v)}f" for v in q["embedding"])
        java_lines.append(f"        q.put(\"{q['text']}\", new float[] {{{vec_parts}}});")
        java_lines.append(f"        e.put(\"{q['text']}\", \"{q['expectId']}\");")

    java_lines.extend([
        "        QUERIES = Map.copyOf(q);",
        "        EXPECTED_TOP = Map.copyOf(e);",
        "    }",
        "}",
    ])

    with open(JAVA_OUT, "w") as f:
        f.write("\n".join(java_lines) + "\n")
    print(f"Wrote {JAVA_OUT}")


if __name__ == "__main__":
    main()
